site_name: AsociaBet API Docs
site_url: https://docs.asocia.bet

docs_dir: src

nav:
  - Home: index.md
  - API Reference:
    - Overview: api/overview.md
    - Authentication: api/authentication.md
    - Endpoints:
      - Twitter API: api/endpoints/twitter.md
      - YouTube API: api/endpoints/youtube.md
  - Integration Guide:
    - Getting Started: integration/getting-started.md
    - Best Practices: integration/best-practices.md

theme:
  name: material
  language: en
  favicon: assets/favicon.ico
  logo: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font: false  # Disable default font loading

  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - search

extra_css:
  - stylesheets/extra.css

# Add social links to footer
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AsociaBet
      name: AsociaBet on Twitter
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/ujmqHhxXgZ
      name: Join our Discord
    - icon: fontawesome/brands/telegram
      link: https://t.me/+GG-JJcZQNTRlYTI0
      name: AsociaBet on Telegram
    - icon: material/web
      link: https://www.asocia.bet
      name: AsociaBet Website
    - icon: material/developer-board
      link: https://dev.asocia.bet
      name: AsociaBet Developer Portal
    - icon: material/tree
      link: https://linktr.ee/asociabet
      name: AsociaBet Linktree
